server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://one-eco.cqzss9l3faaq.ap-northeast-2.rds.amazonaws.com/1eco
    username: admin
    password: test1234
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        jdbc:
          time_zone: UTC
      show-sql: true
      open-in-view: true
      format_sql: true
      use_sql_comments: true
    generate-ddl: false
  redis:
    host: localhost
    port: 6379


  config:
    import:
      - classpath:logback.yml
      - classpath:secretKey.yml
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
